---
- System:
    - Cockpit:
        icon: cockpit.png
        href: http://__HOSTNAME__:9090
        description: System management
    - Tailscale:
        icon: tailscale.png
        description: Private network
        widget:
          type: tailscale
          deviceid: __TAILSCALE_DEVICEID__
          key: < Your Tailscale API Access Token from https://login.tailscale.com/admin/settings/keys >

- Services:
    - Syncthing:
        icon: syncthing.png
        href: http://__HOSTNAME__:8384
        description: File synchronization
        widget:
          type: strelaysrv
          url: http://__HOSTNAME__:8384
