---
- System:
    - Cockpit:
        icon: cockpit.png
        href: http://__HOSTNAME__:9090
        description: System management
    - Tailscale:
        icon: tailscale.png
        href: http://__HOSTNAME__:41641
        description: Private network

- Services:
    - Syncthing:
        icon: syncthing.png
        href: http://__HOSTNAME__:8384
        description: File synchronization
        widget:
          type: strelaysrv
          url: http://__HOSTNAME__:8384
