---
- System:
    - Cockpit:
        icon: cockpit.png
        href: http://__HOSTNAME__:9090
        description: System management
        widget:
          type: cockpit
          url: http://__HOSTNAME__:9090

- Services:
    - Syncthing:
        icon: syncthing.png
        href: http://__HOSTNAME__:8384
        description: File synchronization
        widget:
          type: syncthing
          url: http://__HOSTNAME__:8384
