on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ALMALINUX_VERSION: 10
  IMAGE_NAME: ghcr.io/flyinpancake/hoth-os

jobs:
  gather_metadata:
    runs-on: ubuntu-24.04-arm
    name: Gather Metadata
    outputs:
      tag_alma_version: "${{ steps.get_alma_version.outputs.version }}"
      tag_alma_date: "${{ steps.get_alma_version.outputs.version }}-${{ steps.get_date.outputs.date }}"
      tag_sha: "sha-${{ steps.get_sha.outputs.sha }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Get Commit SHA
        id: get_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get AlmaLinux Version
        id: get_alma_version
        run: echo "version=$ALMALINUX_VERSION" >> $GITHUB_OUTPUT

      - name: Make Date Tag
        id: get_date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
  build_bootc:
    runs-on: ubuntu-24.04-arm
    needs: gather_metadata
    name: Build Bootc Image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Podman
        run: |
          sudo apt update
          sudo apt install -y podman fish
      - name: Build and Push Image
        shell: fish
        run: |
          podman build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ needs.gather_metadata.outputs.tag_alma_version }} -t $IMAGE_NAME:${{ needs.gather_metadata.outputs.tag_alma_date }} -t $IMAGE_NAME:${{ needs.gather_metadata.outputs.tag_sha }} .
          podman push $IMAGE_NAME:latest
          podman push $IMAGE_NAME:${{ needs.gather_metadata.outputs.tag_alma_version }}
          podman push $IMAGE_NAME:${{ needs.gather_metadata.outputs.tag_alma_date }}
          podman push $IMAGE_NAME:${{ needs.gather_metadata.outputs.tag_sha }}